enum SCREENS {
  SPLASH = "#SPLASH",
  APP = "#APP",
  LOGIN = "#LOGIN",
  WELCOME = "#WELCOME",
  HOME = "#HOME",
  LOADING = "#LOADING",
  SETTINGS = "#SETTINGS"
}

enum ASYNC_KEYS {
  ACCESS_TOKEN = '@ACCESS_TOKEN',
  USER_ID = "@USER_ID",
  USER_NAME = "@USER_NAME",
  USER_DATA = "@USER_DATA",
  SONGS = "@SONGS",
  PLAY_LISTS = "@PLAY_LISTS",
  LAYOUT = "@LAYOUT",
  AGENDE = "@AGENDE",
  ENABLE_AGENDA = "@ENABLE_AGENDA",
  ENABLE_WELCOME_SCREEN = "@ENABLE_WELCOME_SCREEN"
}

enum ALERT_TYPES {
  SUCCESS = 'success',
  WARNING = "error",
  DANGER = "error",
  INFO = "info"
}
enum ALERT_HEADER {
  SUCCESS = 'SUCCESS!',
  WARNING = "WARNING!",
  DANGER = "ERROR!",
  INFO = "INFO"
}

enum LAYOUTS {
  PRIMARY = "PRIMARY",
  SECONDARY = "SECONDARY"
}

export {
  SCREENS,
  ASYNC_KEYS,
  ALERT_TYPES,
  ALERT_HEADER,
  LAYOUTS
}